config/routes.rb
Rails.application.routes.draw do

  resources :parts, only: ["index", "new", "create", "show", "update"]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  resources :orders, only: [:index, :show, :update, :new, :create]
  resources :orders do
    resources :orders_parts, only: [:new, :create]
  end

  resources :orders_parts, only: :update
  resources :warehouses, only: [:index, :show, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_parts
  has_many :parts, through: :orders_parts
  belongs_to :creator, class_name: :User, optional: true
  belongs_to :processor, class_name: :User, optional: true
  belongs_to :warehouse

  def houston_time(type)
    if type.to_s == 'created'
      houston_time_handler(self.created_at)
    elsif type.to_s == 'updated'
      houston_time_handler(self.updated_at)
    else
      nil
    end
  end

  private
    def houston_time_handler(time)
      time = time.in_time_zone("Central Time (US & Canada)")
      time.strftime("%Y-%m-%d %H:%M:%S") + " Houston Time"
    end

end

app/models/orders_part.rb
class OrdersPart < ApplicationRecord
  belongs_to :order
  belongs_to :part
  validates :quantity_ordered, presence: true
end

app/models/part.rb
class Part < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :orders_parts
  has_many :orders, through: :orders_parts
  has_many :parts_warehouses
  has_many :warehouses, through: :parts_warehouses
end

app/models/parts_warehouse.rb
class PartsWarehouse < ApplicationRecord
  belongs_to :part
  belongs_to :warehouse
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  validates :first_name, :last_name, :username, presence: true
  has_many :created_orders, foreign_key: :creator_id, :class_name => 'Order'
  has_many :processed_orders, foreign_key: :processor_id, :class_name => 'Order'
  has_secure_password
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :location, presence: true
  has_many :parts_warehouses
  has_many :parts, through: :parts_warehouses
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    redirect_to new_session_path if !session[:user_id]
    @orders = Order.all
  end

  def show
    redirect_to new_session_path if !session[:user_id]
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @errors = []

    submitted = params[:order][:submitted] if params[:order]
    user = User.find(session[:user_id])

    if submitted == "true"
      @order.submitted = true
      @order.save
    elsif params[:part_id]
      params[:part_id].each do |key, value|
        if value == ""
          @errors << "Must add a quantity for every item"
          break
        end
        if value.to_i < 0
          @errors << "Cannot mark less than one item received"
          break
        end
      end
      if @errors.empty?
        @order.processor = user
        params[:part_id].each do |key, value|
          orderpart = OrdersPart.find(key)
          orderpart.quantity_received = value
          orderpart.save
        end
        @order.processed = true
        @order.save
      end
    end
    if @errors.empty?
      redirect_to order_path(@order)
    else
      render "show"
    end
  end

  def new
    redirect_to new_session_path if !session[:user_id]
    redirect_to orders_path unless User.find(session[:user_id]).admin

    warehouses = Warehouse.all
    @warehouse_options = warehouses.map { |warehouse| [warehouse.location, warehouse.id] }

  end

  def create
    warehouse = Warehouse.find(params[:order][:warehouse].to_i)
    @order = Order.create(warehouse: warehouse, creator: User.find(session[:user_id]))


    redirect_to new_order_orders_part_path(@order)
  end
end

app/controllers/orders_parts_controller.rb
class OrdersPartsController < ApplicationController

  def new
    redirect_to new_session_path if !session[:user_id]
    redirect_to orders_path unless User.find(session[:user_id]).admin
    @order = Order.find(params[:order_id])
  end

  def create
    @errors = []
    order = Order.find(params[:order_id])
    part_id = params[:orders_part][:part_id]
    quantity = params[:orders_part][:quantity]

    if part_id == ""
      @errors << "Must enter a part number"
    end
    if quantity == ""
      @errors << "Must enter a quantity"
    end
    if !Part.exists?(part_id)
      @errors << "Could not find part with id #{part_id}"
    end

    if @errors.empty?
      part = Part.find(part_id)
      quantity = quantity.to_i
      @orders_part = OrdersPart.create(order: order, part: part, quantity_ordered: quantity)
      redirect_to order_path(order)
    else
      render 'new', locals: { '@order': order }
    end
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
    redirect_to new_session_path if !session[:user_id]
    @parts = Part.all
  end

  def new
    redirect_to new_session_path if !session[:user_id]
    redirect_to orders_path unless User.find(session[:user_id]).admin
    @part = Part.new
  end

  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to parts_path
    else
      render 'new'
    end
  end

  def show
    redirect_to new_session_path if !session[:user_id]
    @part = Part.find(params[:id])
  end

  def update
    @part = Part.find(params[:id])
    params[:location_part].each do |key,value|
      @warehouse = Warehouse.find(key)
      update = PartsWarehouse.find_by(part: @part, warehouse: @warehouse)

      if update.quantity < value.to_i
        @errors = ['Quantity requested cannot be greater than the current quantity.']
      elsif value.to_i < 1
        @errors = ['Quantity requested must be more than 1']
      else
        update.quantity = update.quantity - value.to_i
        update.save
      end
    end
    render :'show'
  end

private
  def part_params
      params.require(:part).permit(:name, :min, :max)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if session[:user_id]
      redirect_to orders_path
    end
  end

  def create
    user = User.find_by(username: params[:username])
    if user
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to orders_path
      else
        @errors = ['Invalid combination of username/password.']
        render :new
      end
    else
      @errors = ['Invalid combination of username/password.']
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:admin] == "1"
      @user.admin = true
    end

    if @user.save
      flash[:success] = "Successfully created user #{@user.first_name} #{@user.last_name}"
      redirect_to root_path
    else
      render "new"
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def index
    redirect_to new_session_path if !session[:user_id]
    @warehouses = Warehouse.all
  end

  def show
    redirect_to new_session_path if !session[:user_id]
    @warehouse = Warehouse.find(params[:id])
  end

  def update
    @part = Part.find(params[:id])
    params[:location_part].each do |key,value|
      @warehouse = Warehouse.find(key)
      update = PartsWarehouse.find_by(part: @part, warehouse: @warehouse)

      if update.quantity < value.to_i
        @errors = ['Quantity requested cannot be greater than the current quantity.']
      elsif value.to_i < 1
        @errors = ['Quantity requested must be more than 1']
      else
        update.quantity = update.quantity - value.to_i
        update.save
      end
    end
    if @errors
      render :show
    else
      redirect_to  warehouse_path(@warehouse)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def logged_in?
    redirect_to new_session_path if !session[:user_id]
  end
end

app/helpers/orders_parts_helper.rb
module OrdersPartsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/_nav.html.erb
<% if session[:user_id] %>
  <nav>
    <ul class="nav">
      <li><a href="/warehouses">Warehouses</a></li>
      <li><a href="/orders">Orders</a></li>
      <% if User.find(session[:user_id]).admin %>
        <li><a href="/orders/new">New Order</a></li>
      <% end %>
      <li><a href="/parts">Parts</a></li>
      <% if User.find(session[:user_id]).admin %>
        <li><a href="/parts/new">New Part</a></li>
      <% end %>
      <% if User.find(session[:user_id]).admin %>
        <li><a href="/users/new">New User</a></li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rutherford Rocket Labs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kanit">
  </head>

  <body>
    <header>
      <div class="banner">
        <div class="banner-stripe" id="banner-top"></div>
        <div class="banner-stripe" id="banner-mid"></div>
        <div class="banner-stripe" id="banner-bot"></div>
      </div>
      <div class="brandname">RRL</div>
      <div class="logo">  <%= image_tag("logo.png") %> </div>

    </header>
    <% if session[:user_id] %>
      <%= render partial: "layouts/nav", locals: { session: session } %>
    <% end %>

    <div class="yield">
      <% if session[:user_id] %>
        <div class="user-details">
          <p><%= User.find(session[:user_id]).first_name[0] %>. <%= User.find(session[:user_id]).last_name %></p>
          <%= form_tag(session_path(session[:user_id]), method: "delete") do %>
            <%= submit_tag "logout" %>
          <% end %>
        </div>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/orders/_discrepency.html.erb
<% if expected > received %>
  <td class="deficit">
    Deficit: <%= expected - received %>
  </td>
<% elsif expected < received %>
  <td class="surplus">
    Surplus: <%= received - expected %>
  </td>
<% end %>

app/views/orders/_errors.html.erb
<% if errors %>
  <% errors.each do |error| %>
    <p id="error_explanation"> <%= error %></p>
  <% end %>
<% end %>

app/views/orders/_order_details.html.erb
<div class="order-details">
  <% if order.submitted && !order.processed %>
    <p>PLACED: <%= order.houston_time("created") %> by <%= order.creator.first_name %> <%= order.creator.last_name[0] %>  </p>
  <% end %>
  <% if order.submitted && order.processed %>
    <p>PLACED: <%= order.houston_time("created") %> by <%= order.creator.first_name %> <%= order.creator.last_name[0] %>  </p>
    <p>PROCESSED: <%= order.houston_time("updated") %> by <%= order.processor.first_name %> <%= order.processor.last_name[0] %> </p>
  <% end %>
</div>

app/views/orders/_processed.html.erb
<h1>Processed Order</h1>

<table>
  <tr class="list">
    <th class="list">Part #</th>
    <th class="list">Name</th>
    <th class="list">Expected</th>
    <th class="list">Received</th>
  </tr>

  <% @order.orders_parts.each do |orderpart| %>

    <tr class="list">
      <td class="list"><%= orderpart.part_id %></td>
      <td class="list"><%= Part.find(orderpart.part_id).name %></td>
      <td class="list"><%= orderpart.quantity_ordered %></td>
      <td class="list"><%= orderpart.quantity_received %></td>
      <%= render partial: "discrepency", locals: {expected: orderpart.quantity_ordered, received: orderpart.quantity_received} %>
    </tr>
  <% end %>
  </table>

app/views/orders/_status.html.erb
<% if !order.submitted && !order.processed %>
  <td class="order-status unsubmitted">
    <%= link_to "unsubmitted", order_path(order) %>
  </td>
<% elsif order.submitted && !order.processed %>
  <td class="order-status process">
    <%= link_to "process", order_path(order) %>
  </td>
<% elsif order.submitted && order.processed %>
  <td class="order-status processed">
    <%= link_to "processed", order_path(order) %>
  </td>
<% else %>
  <td class="order-status processed">
    <%= link_to "processed", order_path(order) %>
  </td>
<% end %>

app/views/orders/_submitted.html.erb
<table>
  <tr class="list">
    <th class="list">Part #</th>
    <th class="list">Name</th>
    <th class="list">Expected</th>
  </tr>
<% order.orders_parts.each do |orderpart| %>
  <tr class="list">
    <td class="list"><%= orderpart.part_id %></td>
    <td class="list"><%= Part.find(orderpart.part_id).name %></td>
    <td class="list"><%= orderpart.quantity_ordered %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Add part to order", new_order_orders_part_path(order) %>

<%= form_tag(order_path(order), method: "patch") do %>
  <%= hidden_field_tag "order[submitted]", "true" %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/orders/_unprocessed.html.erb
<h1>Unprocessed Order</h1>

<%= render partial: 'errors', locals: {errors: errors} %>

<table>
  <tr class="list">
    <th class="list">Part #</th>
    <th class="list">Name</th>
    <th class="list">Expected</th>
    <th class="list">Received</th>
  </tr>

  <%= form_tag(order_path(@order), method: "patch") do %>

  <% @order.orders_parts.each do |orderpart| %>

    <tr class="list">
      <td class="list"><%= orderpart.part_id %></td>
      <td class="list"><%= Part.find(orderpart.part_id).name %></td>
      <td class="list"><%= orderpart.quantity_ordered %></td>
      <td class="list">
        <%= number_field_tag "part_id[#{orderpart.id}]" %>
      </td>
    </tr>
  <% end %>
    <tr>
      <td><%= submit_tag("Process") %></td>
      <% end %>
    </tr>
  </table>

app/views/orders/_unsubmitted.html.erb
<h1>Unsubmitted Order</h1>

<%= link_to "Add part to order", new_order_orders_part_path(order) %>

<table>
  <tr class="list">
    <th class="list">Part #</th>
    <th class="list">Name</th>
    <th class="list">Expected</th>
  </tr>
<% order.orders_parts.each do |orderpart| %>
  <tr class="list">
    <td class="list"><%= orderpart.part_id %></td>
    <td class="list"><%= Part.find(orderpart.part_id).name %></td>
    <td class="list"><%= orderpart.quantity_ordered %></td>
  </tr>
  <% end %>
</table>


<%= form_tag(order_path(order), method: "patch") do %>
  <%= hidden_field_tag "order[submitted]", "true" %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/orders/index.html.erb
<div class="">
  <h1>Orders</h1>
  <% if flash[:success] %>
    <span style="color: #FF00FF;"><%= flash[:success] %></span>
  <% end %>
  <table class="list">
    <tr>
      <th>Order #</th>
      <th>Date Created</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order)%></td>
        <td><%= order.houston_time("updated") %></td>
        <%= render partial: "status", locals: {order: order} %>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for :order, url: orders_path do |f| %>
  <%= f.label :location %>:
  <%= f.select :warehouse, @warehouse_options %><br />
  <%= f.submit "Create Order" %>

<% end %>

app/views/orders/show.html.erb
<div class="order-conditional-show">
  <% if !@order.submitted %>
    <%= render partial: "unsubmitted", locals: {order: @order, errors: @errors} %>
  <% elsif @order.submitted && !@order.processed %>
    <%= render partial: "unprocessed", locals: {order: @order, errors: @errors} %>
  <% elsif @order.submitted && @order.processed %>
    <%= render partial: "processed", locals: {order: @order, errors: @errors} %>
  <% end %>
</div>
<%= render partial: "order_details", locals: { order: @order } %>

app/views/orders_parts/_errors.html.erb
<% if errors %>
  <% errors.each do |error| %>
    <p id="error_explanation"> <%= error %></p>
  <% end %>
<% end %>

app/views/orders_parts/new.html.erb
<h1>Add part to order</h1>

<%= render partial: 'errors', locals: {errors: @errors} %>

<%= form_for :orders_part, url: order_orders_parts_path do |f| %>
  <%= f.label "Part #" %>:
  <%= f.number_field :part_id %><br />
  <%= f.label "Quantity" %>:
  <%= f.number_field :quantity %><br />

  <%= f.submit "Add Part" %>
<% end %>

<%= link_to "Review Order", order_path(@order) %>

app/views/parts/index.html.erb
<div class="">
  <h1>Parts</h1>
  <table class="list">
    <tr>
      <th>Part #</th>
      <th>Name</th>
      <th>Stock</th>
    </tr>
    <% @parts.each do |part| %>
      <tr>
        <td> <%= part.id %></td>
        <td> <%= link_to part.name, part_path(part) %> </td>
        <td><%= PartsWarehouse.where(part: part).count %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/parts/new.html.erb
<h1>Add part to catalog</h1>

<% if @part.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@part.errors.count, "error") %> prohibited
        this part from being added:
      </h3>
      <ul>
        <% @part.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-div">
  <%= form_for :part, url: parts_path do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %><br/ >
    <%= f.label :min %>:
    <%= f.number_field :min %><br/ >
    <%= f.label :max %>:
    <%= f.number_field :max %><br/ >
    <%= f.submit %>
  <% end %>
</div>

app/views/parts/show.html.erb
<div class="">
  <h1><%= @part.name %></h1>
  <%= render partial: 'errors', locals: {errors: @errors} %>
  <table class="list">
    <tr>
      <th >Location</th>
      <th >Stock</th>
      <th>Quantity to claim</th>
    </tr>
    <% @part.parts_warehouses.each do |parthouse| %>
      <tr>
        <td ><%= link_to parthouse.warehouse.location, warehouse_path(parthouse.warehouse) %></td>
        <td><%= parthouse.quantity%></td>
        <% if parthouse.quantity > 0 %>
        <%= form_tag(part_path(@part), method: "patch") do %>
        <td class="list">
          <%= number_field_tag "location_part[#{parthouse.warehouse.id}]" %>
        </td>
        <td style="border:none"><%= submit_tag("Claim") %></td>
        <% end %>
        <% if parthouse.quantity < 10 %>
          <td class="low-quantity">Stock low!</td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% if flash[:success] %>
  <%= flash[:success] %>
<% end %>

<% if @user.errors.any? %>
  <ul id="error_explanation">
    <% @user.errors.full_messages.each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>


<% end %>

<%= form_for @user do |f| %>
  <%= f.label 'First Name' %>:
  <%= f.text_field :first_name %><br/>

  <%= f.label 'Last Name' %>:
  <%= f.text_field :last_name %><br/>

  <%= f.label 'Username' %>:
  <%= f.text_field :username %><br/>

  <%= f.label 'Password' %>:
  <%= f.password_field :password %><br/>

  <%= f.label 'Manager?' %>:
  <%= f.check_box 'admin' %><br/>

  <%= f.submit "Create User" %>

<% end %>

app/views/warehouses/index.html.erb
<div class="">
  <h1>Warehouses</h1>
  <table class="list">
    <tr>
      <th>Location</th>
    </tr>
    <% @warehouses.each do |house| %>
      <tr>
        <td><%= link_to house.location, warehouse_path(house) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/warehouses/show.html.erb
<div class="">
  <h1><%= @warehouse.location %></h1>
  <%= render partial: 'errors', locals: {errors: @errors} %>
  <table class="list">
    <tr >
      <th>Part #</th>
      <th>Name</th>
      <th>Stock</th>
      <th>Quantity to claim</th>
    </tr>
    <% @warehouse.parts_warehouses.order('part_id ASC').each do |parthouse| %>
      <tr>
        <td><%= parthouse.part.id %></td>
        <td><%= link_to parthouse.part.name, part_path(parthouse.part)%></td>
        <td><%= parthouse.quantity %></td>
        <% if parthouse.quantity > 0 %>
        <%= form_tag(warehouse_path(parthouse.part), method: "patch") do %>
        <td class="list">
          <%= number_field_tag "location_part[#{parthouse.warehouse.id}]" %>
        </td>
        <td style="border:none"><%= submit_tag("Claim") %></td>
        <% end %>
        <% if parthouse.quantity < 10 %>
          <td class="low-quantity">Stock low!</td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </table>
</div>